
skillMetadata:
  sections:
    - name: Device
      fields:
        - name: device_type
          label: Device used
          type: select
          options: "4-Mic Array|option_4mic"
          value: option_4mic
        - name: device_num_pixels
          type: number
          label: Number of Pixels
          value: 12
    - name: Pattern
      fields:
        - name: pixel_pattern
          type: select
          label: Select Feedback Pattern
          options: "Alexa|alexa;Google Home|google"
          value: option_google
